budget_app/urls.py
from django.urls import path

from . import views
app_name = 'budget_app'
urlpatterns = [
    
    #Index page
    path('', views.index, name = "index"),
    path('transactions/', views.transactions, name='transactions'),
    path('transactions/<int:transaction_id>/', views.transaction, name='transaction'),
    path('new_entry/<int:transaction_id>/', views.new_entry, name='new_entry'),
    path('delete/<int:entry_id>/', views.delete_entry, name='delete_entry')
]

budget_log/urls.py
from django.contrib import admin
from django.urls import path, include
app_name = 'budget_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_app.urls'))
]

budget_app/models.py
from django.db import models


    
class Transaction(models.Model):
# Create your models here.
    TransactionType = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (self.TransactionType)

class Entry(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    merchant = models.CharField(max_length=200)
    description = models.TextField()
    transaction_amount = models.FloatField(max_length=10)
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        return str(self.merchant)

budget_app/forms.py
from django import forms

from .models import Entry

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['merchant', 'description', 'transaction_amount']
        labels = {'merchant': 'Merchant', 'description': 'Description', 'transaction_amount': 'Transaction Amount'}

budget_app/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Transaction, Entry
from .forms import EntryForm
# Create your views here.
def index(request):
    return render(request, 'budget_app/index.html')

def transactions(request):
    transactions = Transaction.objects.order_by('date_added')
    context = {"transactions" : transactions}
    return render(request, 'budget_app/transactions.html', context)

def transaction(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    entries = transaction.entry_set.order_by('-date_added')
    context = {'transaction': transaction, 'entries': entries}
    return render(request, 'budget_app/transaction.html', context)

def new_entry(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.transaction = transaction
            new_entry.save()
            return HttpResponseRedirect(reverse('budget_app:transaction', args=[transaction_id]))
    context = {'transaction': transaction, 'form': form}
    return render(request, 'budget_app/new_entry.html', context)

def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    entry.delete()
    return redirect('budget_app:transactions')

budget_app/templates/budget_app/base.html
{% load bootstrap3 %} 

 

<!DOCTYPE html> 

<html lang="en"> 

<head> 

<meta charset="utf-8"> 

<meta http-equiv="X-UA-Compatible" content="=IE-edge"> 

<meta name="viewport" content="width=device-width, initial-scale=1"> 
<title>Budget App</title> 
{% bootstrap_css %} 
{% bootstrap_javascript %} 
</head> 
<body> 

    <!-- Static navbar--> 
    
    <nav class="navbar navbar-default navbar-static-top"> 
    
    <div class="container"> 
    
     
    
    <div class="navbar-header"> 
    
    <button type="button" class="navbar-toggle collapsed" 
    
    data-toggle="collapse" data-target="#navbar" 
    
    aria-expanded="false" aria-controls="navbar"> 
    
    </button> 

    <a class="navbar-brand" href="{% url 'budget_app:index' %}">Budget App</a>
</div> 
    
     
    
<div id="navbar" class="navbar-collapse collapse"> 

<ul class="nav navbar-nav"> 
    <ul class="nav navbar-nav"> 
    
        <li><a href="{% url 'budget_app:transactions' %}">Topics</a></li> 
        
        </ul> 
        
        </div><!--/.nav-collapse--> 
        
        </div> 
        
        </nav> 
        <div class="container"> 
    
     
    
            <div class="page-header"> 
            
            {% block header %}{% endblock header %} 
            
            </div> 
            
            <div> 
            
            {% block content %}{% endblock content %} 
            
            </div> 
            
            </div> 
            
              </body> 
            
            </html> 

budget_app/templates/budget_app/index.html
{% extends "budget_app/base.html" %}
{% csrf_token %}
{% block header %}
<div class="jumbotron"> 
<h1>Track your finances</h1>
</div> 
{% endblock header %}
{% block content %}
<h3>This Budget App will help you achieve the goals you're working toward. Hopefully it will give you an action plan of where your money is going.</h3
{% endblock content %} 

budget_app/templates/budget_app/new_entry.html
{% extends "budget_app/base.html" %}

{% load bootstrap3 %}
{% block content %}

<p><a href="{% url 'budget_app:transaction' transaction.id %}">{{ transaction }}</a></p>

    <p>Add a new entry</p>
        <form action="{% url 'budget_app:new_entry' transaction.id %}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form%}
            <button name="submit">add entry</button>
        </form>

{% endblock content %}

budget_app/templates/budget_app/transaction.html
{% extends 'budget_app/base.html' %}
{% block content %}
<h1> {{transaction}}</h1>

<a href="{% url 'budget_app:new_entry' transaction.id%}">Add a new entry</a>

<table class ="table table-striped"> 
    <thead>
        <tr>
            <th>Merchant</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Date</th>
            <th>Delete Entry</th>
        </tr>
    </thead>
<ul>
    <tbody>
    {% for entry in entries %}
        <tr>
            <td>{{ entry.merchant|linebreaks }}</td>
            <td>{{ entry.description|linebreaks }}</td>
            <td>{{ entry.transaction_amount|linebreaks }}</td>
            <td>{{ entry.date_added|date:'M d, Y H:i' }}</td>

            <td><a href="{% url 'budget_app:delete_entry' entry.id %}">Delete</a></td> 
        </tr>
    {% empty %}
        <li>
            There are not entries for this topic yet.
        </li>
{% endfor %}
    </tbody>
</table>
</ul>


{% endblock content %}

budget_app/templates/budget_app/transactions.html
{% extends "budget_app/base.html" %}

{% block content %}

<h1>Transactions</h1>

<u1>
    {% for transaction in transactions %}
    <h3><li>
        <a href="{% url 'budget_app:transaction' transaction.id %}">{{ transaction }}</a>
    </li></h3>
    {% empty %}
        <li>Currently no transactions.</li>
    {% endfor %}
</u1>

{% endblock content %}